config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      get :dashboard, on: :collection
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  resources :templates
  resources :interviews
  
  get '*a' => 'static_pages#error'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :questions
  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  has_attached_file :image, styles: { thumb: "200x200#" }, convert_options: { thumb: " -gravity center -crop '200x200+0+0'" }, :bucket => 'aidinterview-assets', :default_url => 'no-image.jpg'
  validates_attachment_size :image, less_than: 2.megabytes
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}
end

app/views/templates/_form.html.slim
.form-group
  = form_for @template do |f|
    = render 'shared/error_messages', object: f.object
    h2.bg-info
      = f.label :name, 'Name:'
    = f.text_area :name, :placeholder => "Write a template name", class: 'form-control input-lg', rows: 2
    h2.bg-info
      = f.label :template, 'Questions:'
    = f.collection_select :question_ids, Question.all, :id, :content,\
       {:include_blank => false}, {:multiple => true,  class: 'form-control'}
    = f.submit yield(:button_text), class: 'btn btn-md btn-success col-md-4 col-md-offset-4'

app/views/templates/_question_list.html.slim
-unless @template.questions.empty?
  table
    -@template.questions.each do |q|
      tr
        td.name = q.content

app/views/templates/_template.html.slim
tr.info
  td
    =link_to template_path(template), rel: 'tooltip', title: 'Show template'
      = template.name
  td
    .btn-toolbar aria-label="..." role="toolbar"
      = link_to template_path(template), class: "btn btn-sm btn-info" do
        i.glyphicon.glyphicon-eye-open Show
      = link_to edit_template_path(template), class: "btn btn-sm btn-warning" do
        i.glyphicon.glyphicon-edit Edit
      = link_to template_path(template),   method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do
        i.glyphicon.glyphicon-remove Delete

app/views/templates/edit.html.slim
- provide(:title, 'Edit template')
- provide(:button_text, 'Save changes')
.container.content-area
  h1.center.bg-warning
    | Edit template
  = render 'form'

app/views/templates/index.html.slim
- provide(:title, 'All templates')
.container.content-area
  h1
    | All templates
  .row
    = render 'layouts/messages'
  .row
    .col-sm-3  
      = link_to 'Create new template', new_template_path, class: 'btn btn-md btn-success'
  .col-sm-12
  br
    .center
      = will_paginate
  -if @templates.count <= 10
    br    
  table.table.table-bordered.table-hover
    tr.active
      th.col-sm-4
        h4 Name
      th.col-mdsm-4 colspan="3" width="10%"
        h4 Action
    = render @templates

app/views/templates/new.html.slim
- provide(:title, 'New template')
- provide(:button_text, 'Create template')
.container.content-area
  h1.center.bg-warning
    | New template
  = render 'form'

app/views/templates/show.html.slim
- provide(:title, @template.name)
.container.content-area
  h1.center.jumbotron = @template.name
  = render 'layouts/messages'
  h3.jumbotron
    | Number of questions in #{@template.name} template - #{@template.questions.count}
  ul.questions
    -@template.questions.each do |q|
      li = q.content
  p.center
    = link_to edit_template_path(@template), class: "btn btn-sm btn-warning" do
      i.glyphicon.glyphicon-edit Edit