config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      get :dashboard, on: :collection
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  resources :templates
  resources :interviews
  
  get '*a' => 'static_pages#error'

end

app/models/question.rb
class Question < ActiveRecord::Base
  POSSIBLE_LEVELS = %w(beginner good strong)

  belongs_to :topic
  has_and_belongs_to_many :templates
  validates :content,  presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 65_535 }
  validates :answer,   presence: true, length: { maximum: 65_535 }
  validates :topic,    presence: true
  validates :level,    presence: true, inclusion: { in: POSSIBLE_LEVELS, message: "%{value} is not a valid level" }
end

app/controllers/admin/questions_controller.rb
include ActionView::Helpers::TextHelper

module Admin
  class QuestionsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin
    add_breadcrumb "questions", :admin_questions_path
    def index
      @questions = Question.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end

    def show
      @question = Question.find(params[:id])
      @topic = @question.topic
      add_breadcrumb truncate(@question.content, length: 25), admin_question_path(@question)
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = 'Question does not exist!'
      redirect_to admin_questions_path
    end

    def new
      @question = Question.new
      add_breadcrumb "new question", new_admin_question_path
    end

    def create
      @question = Question.new(question_params)
      if @question.save
        flash[:success] = 'Question was successfully created'
        redirect_to admin_question_path(@question)
      else
        render 'new'
      end
    end

    def edit
      @question = Question.find(params[:id])
      add_breadcrumb truncate(@question.content, length: 25), edit_admin_question_path(@question)
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = 'Question does not exist!'
      redirect_to admin_questions_path
    end

    def update
      @question = Question.find(params[:id])
      if @question.update_attributes(question_params)
        flash[:success] = 'Question updated'
        redirect_to admin_question_path
      else
        render 'edit'
      end
    end

    def destroy
      Question.find(params[:id]).destroy
      flash[:success] = 'Question deleted'
      redirect_to :back
    end

    private

    def question_params
      params.require(:question).permit(:topic_id, :content, :answer, :level)
    end

    def check_admin
      return true if current_user.admin?
      redirect_to authenticated_root_path, notice: 'Access Denied'
    end
  end
end

app/helpers/admin/questions_helper.rb
module Admin
  module QuestionsHelper
    def bar_param(q_level)
      case q_level
      when 'beginner'
        { level: q_level, width: "40%", color: "success" }
      when 'good'
        { level: q_level, width: "66%", color: "warning" }
      when 'strong'
        { level: q_level, width: "100%", color: "danger" }
      end
    end
  end
end

app/views/admin/questions/_form.html.slim
.form-group
  = form_for [:admin, @question], html: { multipart: true } do |f|
    = render 'shared/error_messages', object: f.object
    = f.label :topic_id, "Topic"
    = f.collection_select(:topic_id, Topic.all, :id, :title,\
     {:prompt => 'Select a topic', :disabled => 'Select a topic'}, {class: 'form-control'})
    = f.label 'Level'
    .form-group
      .btn-group data-toggle="buttons"
        - Question::POSSIBLE_LEVELS.each do |val|
          - if @question.level == val
            - choosen = "active"
          = f.label :level, value: val, rel: 'tooltip', title: 'Change level',\
           class: "btn btn-default radio-label #{choosen}" do
            = f.radio_button :level, val, class:"form-radio question"
            | #{val}
    = f.label :content, 'Question'
    = f.text_area :content, :placeholder => "Write a question", class: 'form-control', rows: 6
    = f.label :answer
    = f.text_area :answer, :placeholder => "Write an answer", class: 'form-control', rows: 6
    = f.submit yield(:button_text), class: "btn btn-md btn-success col-md-4 col-md-offset-4"

app/views/admin/questions/_level.html.slim
- param = bar_param(question.level)
.progress
  .progress-bar class = "progress-bar-#{param[:color]}" aria-valuemax="100" role="progressbar" style="width:#{param[:width]}"
  	= "#{param[:level]}"
	

app/views/admin/questions/_question.html.slim
-@questions.each do |question|
  tr.info
    td
      = link_to admin_question_path(question), rel: 'tooltip', title: 'Show question'
        = question.id
    td
      = link_to admin_topic_path(question.topic_id), rel: 'tooltip', title: 'Show topic'
        = question.topic.title
    td
      = link_to admin_question_path(question), rel: 'tooltip', title: 'Show question'
        = truncate(question.content, :length => 70)
    td
      = link_to admin_question_path(question), rel: 'tooltip', title: 'Show question'
        = render "admin/questions/level", question: question
    td
      = link_to edit_admin_question_path(question), rel: 'tooltip', title: 'Edit question', class: "btn btn-sm btn-primary" do
        i.glyphicon.glyphicon-edit
    td
      = link_to admin_question_path(question), method: :delete, data: { confirm: 'Are you sure?' }, rel: 'tooltip', title: 'Delete question', class: "btn btn-sm btn-danger" do
        i.glyphicon.glyphicon-remove 
        

app/views/admin/questions/edit.html.slim
- provide(:title, 'Edit question')
- provide(:button_text, 'Save changes')
.container.content-area
  h1.center
    | Edit question
  = render 'form'

app/views/admin/questions/index.html.slim
- provide(:title, 'All questions')
.container.content-area
  h1
    | All questions
  .row
    = render 'layouts/messages'
  .row
    .col-sm-3  
      = link_to 'Create new question', new_admin_question_path, class: 'btn btn-md btn-success'
  br
  .col-sm-12
    .center
      = will_paginate
  table.table.table-bordered.table-hover
    tr.active
      th width="5%"
        h4 id
      th width="10%"
        h4 Topic
      th width="50%"
        h4 Question
      th width="15%"
        h4 Level
      th colspan="2" width="3%"
        h4 Action
    = render 'question'

app/views/admin/questions/new.html.slim
- provide(:title, 'New question')
- provide(:button_text, 'Create question')
.container.content-area
	h1.center
	  | New question
	= render 'form'

app/views/admin/questions/show.html.slim
- provide(:title, 'Show question')
.container.content-area
  h1.center
    = link_to @topic.title, admin_topic_path(@topic)
  .row
    = render 'layouts/messages'
    .col-md-12.btn-group
      = link_to 'Edit question', edit_admin_question_path, class: 'btn btn-md btn-warning'
      = link_to 'Delete question', admin_question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'   
  h4.center
    | Question:
  .q-width
      = render 'admin/questions/level', question: @question      
  .well.q-width
    = @question.content
  h4.center
    | Answer:
  .well.q-width
    = @question.answer