config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      get :dashboard, on: :collection
      member do
        put :approve
      end
    end
    resources :questions
    resources :topics
  end

  resources :templates
  resources :interviews
  
  get '*a' => 'static_pages#error'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :interviews
  validates :first_name, :last_name, presence: true, length: { maximum: 50 }

  scope :waiting_approval, -> { where.not(approved: true) }

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin
    before_action :load_users, only: [:index, :dashboard]

    def index
      @users = params[:waiting_approval] ? User.waiting_approval : User.all
      @search = @users.search(params[:q] || {})
      @users = @search.result.paginate(page: params[:page] || 1, per_page: 10).order(last_name: :asc)
      add_breadcrumb "users", :admin_users_path
    end

    def dashboard
      @total_questions = Question.count
      @total_topics = Topic.count
    end

    def approve
      User.find(params[:id]).update(approved: true)
      redirect_to admin_users_path, notice: 'User Approved'
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_users_path, notice: 'User not found'
    end

    def destroy
      @user = User.find(params[:id]).destroy
      flash[:success] = 'User deleted'
      redirect_to admin_users_path
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_users_path, notice: 'User not found'
    end

    private

    def check_admin
      return true if current_user.admin?
      redirect_to authenticated_root_path, notice: 'Access Denied'
    end

    def load_users
      @users = User.all
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_filter :configure_permitted_parameters
    add_breadcrumb 'update_profile', :edit_user_registration_path

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
      devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    redirect_to dashboard_admin_users_path if current_user.admin?
    @total_templates = Template.count
    @total_interviews = Interview.count
  end
end

app/helpers/admin/users_helper.rb
module Admin
  module UsersHelper
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_search_form_for.html.slim
form.input-group
  = search_form_for @search, url: admin_users_path do |f|
    = f.text_field :first_name_or_last_name_cont, :placeholder => "Search for...", class: "form-control"
    span.input-group-btn
      = f.submit "Go!", class: 'btn btn-default type="button"'

app/views/admin/users/dashboard.html.slim
- provide(:title, 'Admin dashboard')
.container.content-area
  = render 'layouts/messages'
  .row
    .col-lg-12
      .page-header
        h2.center Welcome #{ current_user.first_name }!
  .row
    = render 'shared/panel',  title: panel_title(@total_questions, 'Questions'),
                              link_to_new: new_admin_question_path,
                              link_to_index: admin_questions_path,
                              glyphicon: 'glyphicon-question-sign'

    = render 'shared/panel',  title: panel_title(@total_topics, 'Topics'),
                              link_to_new: new_admin_topic_path,
                              link_to_index: admin_topics_path,
                              glyphicon: 'glyphicon-th-list'

    = render 'shared/panel',  title: panel_title(@users.count, 'Users'),
                              link_to_index: admin_users_path,
                              glyphicon: 'glyphicon-user'

    = render 'shared/panel',  title: panel_title(@users.waiting_approval.count, 
                                     "#{'User'.pluralize(@users.waiting_approval.count)} waiting approval"),
                              link_to_index: admin_users_path(waiting_approval: true),
                              glyphicon: 'glyphicon-time'

app/views/admin/users/index.html.slim
- provide(:title, 'All users')
.container.content-area
  h1 Users
  .row  
    = render 'layouts/messages'
  row
    = render 'search_form_for'
  br
  .col-sm-12
    .center
      = will_paginate @users

  table.table.table-bordered.table-hover
    tr.active
      th width='5%'
        h4 #
      th width="25%"
        h4 = sort_link(@search, :first_name, 'First Name')
      th width="25%"
        h4 = sort_link(@search, :last_name, 'Last Name')
      th width="30%"
        h4 = sort_link(@search, :email, 'Email')
      th width="10%"
        h4 = sort_link(@search, :approved, 'Approved')
      th width="5%"
        h4 = sort_link(@search, :admin, 'Admin')
    - if @users.empty?
      .alert.alert-danger.not_found role="alert"
        a.close data-dismiss="alert" href="#"  × 
        ul
          li
            | Users not found
    - else
      - @users.each_with_index do |user, index|
        tr.info
          td= index + 1
          td= user.first_name
          td= user.last_name
          td= user.email
          td.text-center
            - if user.approved? 
              i.glyphicon.glyphicon-ok.text-success aria-hidden="true" 
            - else 
              = link_to approve_admin_user_path(user), method: :put, class: 'btn btn-sm btn-success', rel: 'tooltip', title: 'Approve user'
                i.glyphicon.glyphicon-ok
              = link_to admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger', rel: 'tooltip', title: 'Delete user'
                i.glyphicon.glyphicon-remove
          td.text-center
            - if user.admin?
              i.glyphicon.glyphicon-ok.text-success aria-hidden="true"